# Generated by Django 4.2 on 2023-04-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_staffreg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staffreg',
            new_name='staff_reg',
        ),
    ]
