# Generated by Django 4.2 on 2023-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_staffreg_staff_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='staff_reg',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
