# Generated by Django 4.2 on 2023-06-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_create_alter_staff_reg_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('p_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=6)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
