# Generated by Django 4.2 on 2023-06-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_pro_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='create',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='staff_reg',
        ),
        migrations.AlterField(
            model_name='pro_details',
            name='product_id',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
