# Generated by Django 4.2 on 2023-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_delete_category_delete_create_delete_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='pro_details',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
